paths:
  data:
    data_dir: "data"
    raw_dir: "data/raw"
    processed_dir: "data/processed"
    interim_dir: "data/interim"
  reports:
    reports_dir: "reports"
    plots_dir: "reports/plots"
  vector_store:
    fiass_dir: "vector_store/fiass"
    chroma_dir: "vector_store/chroma"
  model:
    model_dir: "models/"  